//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Reports_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OACT
    {
        public string AcctCode { get; set; }
        public string AcctName { get; set; }
        public Nullable<decimal> CurrTotal { get; set; }
        public Nullable<decimal> EndTotal { get; set; }
        public string Finanse { get; set; }
        public string Groups { get; set; }
        public string Budget { get; set; }
        public string Frozen { get; set; }
        public string Free_2 { get; set; }
        public string Postable { get; set; }
        public string Fixed { get; set; }
        public Nullable<short> Levels { get; set; }
        public string ExportCode { get; set; }
        public Nullable<int> GrpLine { get; set; }
        public string FatherNum { get; set; }
        public string AccntntCod { get; set; }
        public string CashBox { get; set; }
        public Nullable<short> GroupMask { get; set; }
        public string RateTrans { get; set; }
        public string TaxIncome { get; set; }
        public string ExmIncome { get; set; }
        public Nullable<int> ExtrMatch { get; set; }
        public Nullable<int> IntrMatch { get; set; }
        public string ActType { get; set; }
        public string Transfered { get; set; }
        public string BlncTrnsfr { get; set; }
        public string OverType { get; set; }
        public string OverCode { get; set; }
        public Nullable<int> SysMatch { get; set; }
        public string PrevYear { get; set; }
        public string ActCurr { get; set; }
        public string RateDifAct { get; set; }
        public Nullable<decimal> SysTotal { get; set; }
        public Nullable<decimal> FcTotal { get; set; }
        public string Protected { get; set; }
        public string RealAcct { get; set; }
        public string Advance { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FrgnName { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> ExtraSum { get; set; }
        public string Project { get; set; }
        public string RevalMatch { get; set; }
        public string DataSource { get; set; }
        public string LocMth { get; set; }
        public Nullable<int> MTHCounter { get; set; }
        public Nullable<int> BNKCounter { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string LocManTran { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string ValidFor { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string ValidComm { get; set; }
        public string FrozenFor { get; set; }
        public Nullable<System.DateTime> FrozenFrom { get; set; }
        public Nullable<System.DateTime> FrozenTo { get; set; }
        public string FrozenComm { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Segment_0 { get; set; }
        public string Segment_1 { get; set; }
        public string Segment_2 { get; set; }
        public string Segment_3 { get; set; }
        public string Segment_4 { get; set; }
        public string Segment_5 { get; set; }
        public string Segment_6 { get; set; }
        public string Segment_7 { get; set; }
        public string Segment_8 { get; set; }
        public string Segment_9 { get; set; }
        public string FormatCode { get; set; }
        public string CfwRlvnt { get; set; }
        public string ExchRate { get; set; }
        public string RevalAcct { get; set; }
        public Nullable<decimal> LastRevBal { get; set; }
        public Nullable<System.DateTime> LastRevDat { get; set; }
        public string DfltVat { get; set; }
        public string VatChange { get; set; }
        public Nullable<int> Category { get; set; }
        public string TransCode { get; set; }
        public string OverCode5 { get; set; }
        public string OverCode2 { get; set; }
        public string OverCode3 { get; set; }
        public string OverCode4 { get; set; }
        public string DfltTax { get; set; }
        public string TaxPostAcc { get; set; }
        public string AcctStrLe { get; set; }
        public string MeaUnit { get; set; }
        public string BalDirect { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string PlngLevel { get; set; }
        public string MultiLink { get; set; }
        public string PrjRelvnt { get; set; }
        public string Dim1Relvnt { get; set; }
        public string Dim2Relvnt { get; set; }
        public string Dim3Relvnt { get; set; }
        public string Dim4Relvnt { get; set; }
        public string Dim5Relvnt { get; set; }
        public string AccrualTyp { get; set; }
        public Nullable<int> DatevAcct { get; set; }
        public string DatevAutoA { get; set; }
        public string DatevFirst { get; set; }
        public Nullable<int> SnapShotId { get; set; }
        public string PCN874Rpt { get; set; }
        public string SCAdjust { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPLName { get; set; }
        public string SubLedgerN { get; set; }
        public string VATRegNum { get; set; }
        public string ActId { get; set; }
        public string ClosingAcc { get; set; }
        public string PurpCode { get; set; }
        public string RefCode { get; set; }
        public string BlocManPos { get; set; }
    }
}
