//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Reports_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCRG
    {
        public short GroupCode { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> PriceList { get; set; }
        public string DiscRel { get; set; }
    }
}
