//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Reports_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUSR
    {
        public short USERID { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORD1 { get; set; }
        public string PASSWORD2 { get; set; }
        public short INTERNAL_K { get; set; }
        public string USER_CODE { get; set; }
        public string U_NAME { get; set; }
        public Nullable<short> GROUPS { get; set; }
        public string PASSWORD4 { get; set; }
        public string ALLOWENCES { get; set; }
        public string SUPERUSER { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public string PASSWORD3 { get; set; }
        public string Info1File { get; set; }
        public Nullable<short> Info1Field { get; set; }
        public string Info2File { get; set; }
        public Nullable<short> Info2Field { get; set; }
        public string Info3File { get; set; }
        public Nullable<short> Info3Field { get; set; }
        public string Info4File { get; set; }
        public Nullable<short> Info4Field { get; set; }
        public string dType { get; set; }
        public string E_Mail { get; set; }
        public string PortNum { get; set; }
        public string OutOfOffic { get; set; }
        public string SendEMail { get; set; }
        public string SendSMS { get; set; }
        public string DfltsGroup { get; set; }
        public string CashLimit { get; set; }
        public Nullable<decimal> MaxCashSum { get; set; }
        public string Fax { get; set; }
        public string SendFax { get; set; }
        public string Locked { get; set; }
        public Nullable<short> Department { get; set; }
        public Nullable<short> Branch { get; set; }
        public byte[] UserPrefs { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<short> Charset { get; set; }
        public string OpenCdt { get; set; }
        public Nullable<int> CdtPrvDays { get; set; }
        public string DsplyRates { get; set; }
        public string AuImpRates { get; set; }
        public string OpenDps { get; set; }
        public string RcrFlag { get; set; }
        public string CheckFiles { get; set; }
        public string OpenCredit { get; set; }
        public Nullable<short> CreditDay1 { get; set; }
        public Nullable<short> CreditDay2 { get; set; }
        public string WallPaper { get; set; }
        public Nullable<short> WllPprDsp { get; set; }
        public string AdvImagePr { get; set; }
        public string ContactLog { get; set; }
        public Nullable<System.DateTime> LastWarned { get; set; }
        public Nullable<short> AlertPolFr { get; set; }
        public Nullable<short> ScreenLock { get; set; }
        public string ShowNewMsg { get; set; }
        public string Picture { get; set; }
        public string Position { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string EnbMenuFlt { get; set; }
        public string objType { get; set; }
        public Nullable<int> logInstanc { get; set; }
        public Nullable<short> userSign { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<short> userSign2 { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string OneLogPwd { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public string LastPwds { get; set; }
        public string LastPwds2 { get; set; }
        public Nullable<System.DateTime> LastPwdSet { get; set; }
        public Nullable<int> FailedLog { get; set; }
        public string PwdNeverEx { get; set; }
        public Nullable<decimal> SalesDisc { get; set; }
        public Nullable<decimal> PurchDisc { get; set; }
        public Nullable<System.DateTime> LstLogoutD { get; set; }
        public Nullable<int> LstLoginT { get; set; }
        public Nullable<int> LstLogoutT { get; set; }
        public Nullable<int> LstPwdChT { get; set; }
        public string LstPwdChB { get; set; }
        public string RclFlag { get; set; }
        public string MobileUser { get; set; }
        public string MobileIMEI { get; set; }
        public string PrsWkCntEb { get; set; }
        public Nullable<int> SnapShotId { get; set; }
        public string STData { get; set; }
        public string SupportUsr { get; set; }
        public Nullable<short> NoSTPwdNum { get; set; }
        public string DomainUser { get; set; }
        public string CUSAgree { get; set; }
        public string EmailSig { get; set; }
        public Nullable<short> TPLId { get; set; }
        public string DigCrtPath { get; set; }
        public string ShowNewTsk { get; set; }
        public string IntgrtEb { get; set; }
        public string AllBrnchF { get; set; }
        public string EvtNotify { get; set; }
    }
}
